### ISSUE TITLE
Docker artifact version not displaying correctly in environments UI

### ISSUE THREAD

**Issue by michaelgalloway** [spinnaker/keel#1115]
Looking at the environments view for my internal test application `tempermentalbunny`, I noticed that the version information for my artifact isn't displayed correctly in the details view.

<img width="1193" alt="Screen Shot 2020-05-05 at 11 24 21 AM" src="https://user-images.githubusercontent.com/50880548/81101665-54c22d00-8ec3-11ea-934e-747e553a891d.png">

**Comment by erikmunson** [comment]
this is because your manifest is using the default `tagVersionStrategy`, which is `semver-tag`. Since we expect the version string we're parsing is just a raw semver string we totally mess up all our special logic to show meaningful strings. The strategy you'd want is [`branch-job-commit-by-job`](https://manuals.netflix.net/view/spinnaker/mkdocs/master/Managed-Delivery/dev-docs/artifacts/#basic-configuration).

**Comment by michaelgalloway** [comment]
Updating config manually. 

This will be addressed with an update to the newt export functionality, which will pick up the tag version strategy correctly moving forward.
