### ISSUE TITLE
UI support for entity tags on multi-region resources

### ISSUE THREAD

**Issue by asher** [spinnaker/keel#481]
Keel currently creates entity tag id's with a `*` for region for multi-region capable resources. Example:  
```
"id": "aws:security-group:emburnstest-managed:111111111111:*",
"idPattern": "{{cloudProvider}}:{{entityType}}:{{entityId}}:{{account}}:{{region}}",
```
for ```"keelResourceId": "ec2:security-group:test:emburnstest-managed"``` which can span multiple regions. It looks like deck can't currently map the `*` in the region field to individual regional security groups, so they lack the "managed by spinnaker" designator.

**Comment by emjburns** [comment]
@erikmunson

**Comment by erikmunson** [comment]
So, here's what's hard about this in our current architecture.

Deck gets back a big blob of stuff from clouddriver, spread across N regions. Some of that stuff might be managed, some of it might not. Then there's this entity tag, which says 'this thing is managed in *some* number of regions' without saying which. Now Deck is left to guess which of the N regions it sees for a given thing are under that entity tag's scope. We could leave out the `*` entirely (i.e. not put a region in), which Deck would accept as a global tag and put on the whole cluster. In my opinion, though, categorizing the un-managed region thing as an edge case to handle later is likely not the right call here, as we're already walking the line of user confidence and small misrepresentations have outsized impact on our perceived trustworthiness. My suggestions:

- **For now:** when we do tagging can we take a multi-region resource spec and explode it out into multiple regional tags? The UX will be kind of amusing for a short time because the entity tag will be visually applied to each region of a cluster instead of a global location in the UI, but it avoids the misrepresentation problem while we move forward on the next thing...
- **Going forward:** I'm working out how we can move beyond entity tagging for surfacing resource-related data in Deck, partly because entity tagging is brittle for this use case (though it was a great first iteration) but also because we'll need fresh API data anyway to show real time resource status. Ideally I'd like us to move quickly toward a Gate-powered approach which will hopefully help us alleviate these tag-related difficulties, and am currently focusing my energy there.
