### ISSUE TITLE
Revisit resource spec modeling w.r.t. defaults and exporting

### ISSUE THREAD

**Issue by gal-yardeni** [spinnaker/keel#640]
Relevant slack thread:

Erik Munson:managed: 4:43 PM
potentially :hot_pepper: take I would like people's thoughts on: if we add a new piece of functionality to a resource spec, as part of the work to add that functionality three things should be included:
- Actual functionality on the spec
- The ability to default the spec, using good judgment case-by-case to decide how 'smart' a default should be
- Proper handling of defaults/other cases when exporting that resource
I say this because I've observed that as we add things, the cognitive load and coordination overhead of trying to do 1, 2, and 3 separately when we notice they haven't been done is somewhat of a drag on our focus, and as more folks adopt MD the thrash of each new feature going through 1 -> 2 -> 3 separately will likely be even more jarring/confusing.
:heavy_plus_sign:
1

Luis Pollo 4:45 PM
makes sense to me… I think part of the challenge is that the code to handle those things is also scattered across different classes, and there’s not really a framework to easily implement them
:heavy_plus_sign:
1

I haven’t fully given up on coming up with a more generic solution to define/omit defaults
But haven’t had time to think it through yet
Erik Munson:managed: 4:46 PM
i agree re: things being scattered — i've been wondering if making an effort to address all three concerns in the same cognitive cycle would help us feel and identify that pain to make it better vs. the current state where each piece of the pain is spread around to a different person, week, cognitive cycle etc.
Rob Fletcher:voidchicken: 4:46 PM
I was talking to Emily about exactly this earlier today
Erik Munson:managed: 4:47 PM
lovely. perhaps less controversial than i anticipated :slightly_smiling_face:
Luis Pollo 4:47 PM
any conclusions @fletch?
Rob Fletcher:voidchicken: 4:47 PM
no
just that I was worried it would be easy to forget about the export bit
but the export is vital functionality
Luis Pollo 4:50 PM
let me give it some thought as I pick up #625 reported by @erikmunson

**Comment by luispollo** [comment]
Relevant slack thread:

Erik Munson:managed: 4:43 PM
potentially :hot_pepper: take I would like people's thoughts on: if we add a new piece of functionality to a resource spec, as part of the work to add that functionality three things should be included:
- Actual functionality on the spec
- The ability to default the spec, using good judgment case-by-case to decide how 'smart' a default should be
- Proper handling of defaults/other cases when exporting that resource
I say this because I've observed that as we add things, the cognitive load and coordination overhead of trying to do 1, 2, and 3 separately when we notice they haven't been done is somewhat of a drag on our focus, and as more folks adopt MD the thrash of each new feature going through 1 -> 2 -> 3 separately will likely be even more jarring/confusing.
:heavy_plus_sign:
1


Luis Pollo 4:45 PM
makes sense to me… I think part of the challenge is that the code to handle those things is also scattered across different classes, and there’s not really a framework to easily implement them
:heavy_plus_sign:
1

I haven’t fully given up on coming up with a more generic solution to define/omit defaults
But haven’t had time to think it through yet
Erik Munson:managed: 4:46 PM
i agree re: things being scattered — i've been wondering if making an effort to address all three concerns in the same cognitive cycle would help us feel and identify that pain to make it better vs. the current state where each piece of the pain is spread around to a different person, week, cognitive cycle etc.
Rob Fletcher:voidchicken: 4:46 PM
I was talking to Emily about exactly this earlier today
Erik Munson:managed: 4:47 PM
lovely. perhaps less controversial than i anticipated :slightly_smiling_face:
Luis Pollo 4:47 PM
any conclusions @fletch?
Rob Fletcher:voidchicken: 4:47 PM
no
just that I was worried it would be easy to forget about the export bit
but the export is vital functionality
Luis Pollo 4:50 PM
let me give it some thought as I pick up #625 reported by @erikmunson
